# Generated by Django 5.2.3 on 2025-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VieseerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='categories',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='user_uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Теги (через запятую)'),
        ),
    ]
