# Generated by Django 5.2.3 on 2025-06-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VieseerApp', '0002_rename_upload_date_image_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
