# Generated by Django 5.2.3 on 2025-07-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VieseerApp', '0005_image_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionimage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='collectionimage',
            unique_together={('collection', 'image')},
        ),
    ]
